"use client";

/**
 * ui-strings.js
 * Centralised UI strings for all page components.
 * Usage (client component):
 *   import { useUI } from "@/lib/ui-strings";
 *   const ui = useUI();
 *   <button>{ui.save}</button>
 *
 * Or without hook (e.g. inside a non-hook context):
 *   import { getUI } from "@/lib/ui-strings";
 *   const ui = getUI("en");
 */

export const UI_STRINGS = {
  en: {
    // ── Common actions ─────────────────────────────────────────
    save: "Save",
    saving: "Saving…",
    saved: "Saved",
    cancel: "Cancel",
    delete: "Delete",
    deleting: "Deleting…",
    edit: "Edit",
    add: "Add",
    create: "Create",
    creating: "Creating…",
    update: "Update",
    close: "Close",
    back: "Back",
    next: "Next",
    previous: "Previous",
    confirm: "Confirm",
    remove: "Remove",
    search: "Search",
    filter: "Filter",
    reset: "Reset",
    apply: "Apply",
    loading: "Loading…",
    loadingMore: "Loading more…",
    noResults: "No results found",
    noData: "No data available",
    error: "An error occurred",
    retry: "Retry",
    upload: "Upload",
    uploading: "Uploading…",
    download: "Download",
    export: "Export",
    import: "Import",
    send: "Send",
    print: "Print",
    preview: "Preview",
    publish: "Publish",
    unpublish: "Unpublish",
    archive: "Archive",
    duplicate: "Duplicate",
    select: "Select",
    selectAll: "Select all",
    deselectAll: "Deselect all",
    selected: "selected",
    actions: "Actions",
    more: "More",
    show: "Show",
    hide: "Hide",
    expand: "Expand",
    collapse: "Collapse",
    copy: "Copy",
    paste: "Paste",
    refresh: "Refresh",
    viewDetails: "View details",
    viewAll: "View all",

    // ── Status labels ──────────────────────────────────────────
    status: "Status",
    statusOpen: "Open",
    statusInProgress: "In Progress",
    statusCompleted: "Completed",
    statusCancelled: "Cancelled",
    statusPaid: "Paid",
    statusUnpaid: "Unpaid",
    statusPartiallyRefunded: "Partially Refunded",
    statusRefunded: "Refunded",
    statusShipped: "Shipped",
    statusDelivered: "Delivered",
    statusReturn: "Return",
    statusReturnRequested: "Return Requested",
    statusDraft: "Draft",
    statusPublished: "Published",
    statusArchived: "Archived",
    statusActive: "Active",
    statusInactive: "Inactive",

    // ── Table headers ──────────────────────────────────────────
    colNumber: "#",
    colName: "Name",
    colTitle: "Title",
    colEmail: "Email",
    colPhone: "Phone",
    colAddress: "Address",
    colCity: "City",
    colCountry: "Country",
    colDate: "Date",
    colCreatedAt: "Created",
    colUpdatedAt: "Updated",
    colAmount: "Amount",
    colTotal: "Total",
    colPrice: "Price",
    colQuantity: "Quantity",
    colInventory: "Inventory",
    colStatus: "Status",
    colPaymentStatus: "Payment Status",
    colDeliveryStatus: "Delivery Status",
    colOrderStatus: "Order Status",
    colOrderNumber: "Order #",
    colCustomer: "Customer",
    colProduct: "Product",
    colSKU: "SKU",
    colImage: "Image",
    colRating: "Rating",
    colReview: "Review",
    colType: "Type",
    colCategory: "Category",
    colDescription: "Description",
    colActions: "Actions",
    colColumns: "Columns",
    colSeller: "Seller",

    // ── Orders page ────────────────────────────────────────────
    orders: "Orders",
    orderNumber: "Order number",
    orderStatus: "Order status",
    paymentStatus: "Payment status",
    deliveryStatus: "Delivery status",
    allStatuses: "All statuses",
    allPayments: "All payments",
    allDeliveries: "All deliveries",
    addOrder: "Add order",
    manualOrder: "Manual Order",
    ship: "Ship",
    buyLabel: "Buy label",
    cancelOrder: "Cancel order",
    deleteOrder: "Delete order",
    viewDetails: "View details",
    shippingTracking: "Shipping / Tracking",
    carrier: "Carrier",
    noCarrier: "No carrier registered",
    trackingNumber: "Tracking number",
    enterTrackingNumber: "Enter tracking number",
    savedTracking: "Saved:",
    clickTracking: "— Click to open tracking",
    noTrackingYet: "No tracking number saved yet.",
    invoice: "Invoice (PDF)",
    deliveryNote: "Delivery note (PDF)",
    message: "Message",
    sortNewestFirst: "Newest first",
    sortOldestFirst: "Oldest first",
    amountDesc: "Amount ↓",
    amountAsc: "Amount ↑",
    searchSeller: "Search seller",
    sellerGroups: "Sort seller groups",
    bulkShip: "Ship",
    bulkPackaging: "Packaging center",
    clearSelection: "Clear selection",
    noOrders: "No orders found",
    loadingOrders: "Loading orders…",
    product: "Product",
    qty: "Qty",
    unitPrice: "Unit price (gross)",
    total: "Total (gross)",
    noItems: "No items",
    net: "Net",
    shipping: "Shipping",
    shippingFree: "Free",
    subtotal: "Subtotal (gross)",
    grandTotal: "Grand total",
    guestBadge: "Guest",
    reviewsTitle: "Customer reviews",
    noReviews: "No reviews available.",
    labelSuccess: "Label created successfully!",
    labelError: "Error creating label",
    labelPrint: "Print label (PDF)",
    customerData: "Customer data",
    firstName: "First name",
    lastName: "Last name",
    phone: "Phone",
    country: "Country",
    street: "Street",
    postalCode: "Postal code",
    city: "City",
    items: "Items",
    itemName: "Name",
    itemQty: "Qty",
    itemPrice: "Price (cents)",
    addItem: "Add item",
    shippingCents: "Shipping (cents)",
    discountCents: "Discount (cents)",
    orderStatusLabel: "Order status",
    paymentStatusLabel: "Payment status",
    deliveryStatusLabel: "Delivery status",
    paymentMethod: "Payment method",
    currency: "Currency",
    notes: "Notes",
    summarySubtotal: "Subtotal",
    summaryShipping: "Shipping",
    summaryDiscount: "Discount",
    summaryTotal: "Total",
    createOrder: "Create order",
    filterAndSort: "Filter & sort",
    searchPlaceholder: "Name, email, order number…",
    return: "Return",
    activeReturn: "Return (active)",
    retoure: "Return",

    // ── Customers page ─────────────────────────────────────────
    customers: "Customers",
    customer: "Customer",
    addCustomer: "Add customer",
    editCustomer: "Edit customer",
    deleteCustomer: "Delete customer",
    noCustomers: "No customers found",
    guestCustomer: "Guest",
    businessCustomer: "Business",
    privateCustomer: "Private",
    totalOrders: "Total orders",
    totalSpent: "Total spent",
    lastOrder: "Last order",
    accountType: "Account type",

    // ── Products page ──────────────────────────────────────────
    products: "Products",
    addProduct: "Add product",
    editProduct: "Edit product",
    deleteProduct: "Delete product",
    noProducts: "No products found",
    productTitle: "Product title",
    productDescription: "Description",
    productPrice: "Price",
    productInventory: "Inventory",
    variants: "Variants",
    showVariants: "Show variants",
    hideVariants: "Hide variants",
    saveVariants: "Save variants",
    savingVariants: "Saving…",
    variantName: "Variant name",
    variantPrice: "Price",
    variantInventory: "Stock",
    variantSku: "SKU",

    // ── Settings ────────────────────────────────────────────────
    settings: "Settings",
    settingsBack: "Back",
    settingsTitle: "Settings",
    settingsSubtitle: "Configure platform",
    settingsGroupAccount: "Account",
    settingsGroupTeam: "Team",
    settingsGroupShop: "Shop",
    settingsGroupSystem: "System",
    settingsGeneral: "General",
    settingsVerification: "Verification",
    settingsBilling: "Billing",
    settingsSecurity: "Security",
    settingsUsers: "Users & Permissions",
    settingsPayments: "Payments",
    settingsCheckout: "Checkout",
    settingsShipping: "Shipping & Delivery",
    settingsTaxes: "Taxes",
    settingsLocations: "Locations",
    settingsIntegrations: "Apps & Integrations",
    settingsNotifications: "Notifications",

    // ── General settings ───────────────────────────────────────
    storeName: "Store name",
    email: "Email",
    companyName: "Company legal name",
    taxId: "Tax ID",
    vatId: "VAT ID",
    iban: "IBAN (optional)",
    website: "Website",
    language: "Language",
    address: "Address",
    postalCode: "Postal code",
    savedSuccess: "Settings saved successfully.",
    saveError: "Failed to save settings.",
    businessAddress: "Registered business address",
    warehouseAddress: "Warehouse / return address",
    documents: "Company documents",
    uploading: "Uploading documents…",
    adminInfo: "Admin Information (Platform operator)",
    adminInfoNote: "These details appear in signed Seller Agreement PDFs. Visible to superusers only.",

    // ── Billing ─────────────────────────────────────────────────
    orderDocuments: "Order Documents",
    commissionInvoices: "Commission Invoices",
    searchOrderPlaceholder: "Order no. or customer name…",
    from: "From",
    to: "To",
    documentType: "Document type",
    allDocuments: "All documents",
    invoiceDoc: "Invoice",
    deliveryNoteDoc: "Delivery note",
    shippingLabel: "Shipping label",
    returnDoc: "Return",
    csvExport: "CSV Export",
    openInvoices: "Open invoices",
    noOrdersFound: "No orders found.",
    period: "Period",
    type: "Type",
    amount: "Amount",
    downloadAll: "Download all",
    backfill: "Backfill",
    noInvoices: "No commission invoices yet.",
    noInvoicesNote: "Commission invoices will appear here once the platform provides them.",
    platformOwn: "Platform (own)",
    sellerOrders: "Seller orders",
    noSellerOrders: "No more seller orders",
    superuserSection: "Your superuser area — own account orders and unassigned",
    noOrdersInSection: "No orders in this section.",

    // ── Notifications ──────────────────────────────────────────
    notifications: "Notifications",
    noNotifications: "No notifications",
    markAsRead: "Mark as read",
    markAllRead: "Mark all as read",

    // ── Misc ───────────────────────────────────────────────────
    netto: "Net",
    brutto: "Gross",
    all: "All",
    yes: "Yes",
    no: "No",
    optional: "optional",
    required: "required",
    new: "New",
    active: "Active",
    inactive: "Inactive",
    unknown: "Unknown",
  },

  de: {
    // ── Common actions ─────────────────────────────────────────
    save: "Speichern",
    saving: "Wird gespeichert…",
    saved: "Gespeichert",
    cancel: "Abbrechen",
    delete: "Löschen",
    deleting: "Wird gelöscht…",
    edit: "Bearbeiten",
    add: "Hinzufügen",
    create: "Erstellen",
    creating: "Wird erstellt…",
    update: "Aktualisieren",
    close: "Schließen",
    back: "Zurück",
    next: "Weiter",
    previous: "Zurück",
    confirm: "Bestätigen",
    remove: "Entfernen",
    search: "Suche",
    filter: "Filtern",
    reset: "Zurücksetzen",
    apply: "Anwenden",
    loading: "Laden…",
    loadingMore: "Mehr laden…",
    noResults: "Keine Ergebnisse gefunden",
    noData: "Keine Daten verfügbar",
    error: "Ein Fehler ist aufgetreten",
    retry: "Erneut versuchen",
    upload: "Hochladen",
    uploading: "Wird hochgeladen…",
    download: "Herunterladen",
    export: "Exportieren",
    import: "Importieren",
    send: "Senden",
    print: "Drucken",
    preview: "Vorschau",
    publish: "Veröffentlichen",
    unpublish: "Verstecken",
    archive: "Archivieren",
    duplicate: "Duplizieren",
    select: "Auswählen",
    selectAll: "Alle auswählen",
    deselectAll: "Auswahl aufheben",
    selected: "ausgewählt",
    actions: "Aktionen",
    more: "Mehr",
    show: "Anzeigen",
    hide: "Ausblenden",
    expand: "Aufklappen",
    collapse: "Zuklappen",
    copy: "Kopieren",
    paste: "Einfügen",
    refresh: "Aktualisieren",
    viewDetails: "Details anzeigen",
    viewAll: "Alle anzeigen",

    // ── Status labels ──────────────────────────────────────────
    status: "Status",
    statusOpen: "Offen",
    statusInProgress: "In Bearbeitung",
    statusCompleted: "Abgeschlossen",
    statusCancelled: "Storniert",
    statusPaid: "Bezahlt",
    statusUnpaid: "Offen",
    statusPartiallyRefunded: "Teil erstattet",
    statusRefunded: "Erstattet",
    statusShipped: "Versendet",
    statusDelivered: "Zugestellt",
    statusReturn: "Retoure",
    statusReturnRequested: "Retoure Anfrage",
    statusDraft: "Entwurf",
    statusPublished: "Veröffentlicht",
    statusArchived: "Archiviert",
    statusActive: "Aktiv",
    statusInactive: "Inaktiv",

    // ── Table headers ──────────────────────────────────────────
    colNumber: "Nr.",
    colName: "Name",
    colTitle: "Titel",
    colEmail: "E-Mail",
    colPhone: "Telefon",
    colAddress: "Adresse",
    colCity: "Stadt",
    colCountry: "Land",
    colDate: "Datum",
    colCreatedAt: "Erstellt",
    colUpdatedAt: "Aktualisiert",
    colAmount: "Betrag",
    colTotal: "Gesamt",
    colPrice: "Preis",
    colQuantity: "Menge",
    colInventory: "Bestand",
    colStatus: "Status",
    colPaymentStatus: "Zahlungsstatus",
    colDeliveryStatus: "Lieferstatus",
    colOrderStatus: "Bestellstatus",
    colOrderNumber: "Bestellnummer",
    colCustomer: "Kunde",
    colProduct: "Produkt",
    colSKU: "SKU",
    colImage: "Bild",
    colRating: "Bewertung",
    colReview: "Bewertung",
    colType: "Typ",
    colCategory: "Kategorie",
    colDescription: "Beschreibung",
    colActions: "Aktionen",
    colColumns: "Spalten",
    colSeller: "Verkäufer",

    // ── Orders page ────────────────────────────────────────────
    orders: "Bestellungen",
    orderNumber: "Bestellnummer",
    orderStatus: "Bestellstatus",
    paymentStatus: "Zahlungsstatus",
    deliveryStatus: "Lieferstatus",
    allStatuses: "Alle Status",
    allPayments: "Alle Zahlungen",
    allDeliveries: "Alle Lieferungen",
    addOrder: "Bestellung hinzufügen",
    manualOrder: "Manuelle Bestellung",
    ship: "Versenden",
    buyLabel: "Etikett kaufen",
    cancelOrder: "Stornieren",
    deleteOrder: "Löschen",
    viewDetails: "Details anzeigen",
    shippingTracking: "Versand / Tracking",
    carrier: "Dienstleister",
    noCarrier: "Kein Versanddienstleister hinterlegt",
    trackingNumber: "Trackingnummer",
    enterTrackingNumber: "Trackingnummer eintragen",
    savedTracking: "Gespeichert:",
    clickTracking: "— Klick öffnet die Sendungsverfolgung",
    noTrackingYet: "Noch keine Trackingnummer gespeichert.",
    invoice: "Rechnung (PDF)",
    deliveryNote: "Lieferschein (PDF)",
    message: "Nachricht",
    sortNewestFirst: "Neu zuerst",
    sortOldestFirst: "Älteste zuerst",
    amountDesc: "Betrag ↓",
    amountAsc: "Betrag ↑",
    searchSeller: "Verkäufer suchen",
    sellerGroups: "Verkäufer-Gruppen sortieren",
    bulkShip: "Versenden",
    bulkPackaging: "Verpackungszentrum",
    clearSelection: "Auswahl aufheben",
    noOrders: "Keine Bestellungen gefunden",
    loadingOrders: "Laden…",
    product: "Produkt",
    qty: "Menge",
    unitPrice: "Einzelpreis (brutto)",
    total: "Gesamt (brutto)",
    noItems: "Keine Artikel",
    net: "Netto",
    shipping: "Versandkosten",
    shippingFree: "Kostenlos",
    subtotal: "Zwischensumme (brutto)",
    grandTotal: "Gesamtkosten",
    guestBadge: "Gast",
    reviewsTitle: "Kundenbewertungen",
    noReviews: "Keine Bewertungen vorhanden.",
    labelSuccess: "Etikett erfolgreich erstellt!",
    labelError: "Fehler beim Etikett erstellen",
    labelPrint: "Etikett drucken (PDF)",
    customerData: "Kundendaten",
    firstName: "Vorname",
    lastName: "Nachname",
    phone: "Telefon",
    country: "Land",
    street: "Straße",
    postalCode: "PLZ",
    city: "Stadt",
    items: "Artikel",
    itemName: "Bezeichnung",
    itemQty: "Menge",
    itemPrice: "Preis (Cent)",
    addItem: "Artikel hinzufügen",
    shippingCents: "Versand (Cent)",
    discountCents: "Rabatt (Cent)",
    orderStatusLabel: "Bestellstatus",
    paymentStatusLabel: "Zahlungsstatus",
    deliveryStatusLabel: "Lieferstatus",
    paymentMethod: "Zahlungsmethode",
    currency: "Währung",
    notes: "Notizen",
    summarySubtotal: "Zwischensumme",
    summaryShipping: "Versand",
    summaryDiscount: "Rabatt",
    summaryTotal: "Gesamt",
    createOrder: "Bestellung erstellen",
    filterAndSort: "Filtern & sortieren",
    searchPlaceholder: "Name, E-Mail, Bestellnummer…",
    return: "Retoure",
    activeReturn: "Retoure (aktiv)",
    retoure: "Retoure",

    // ── Customers page ─────────────────────────────────────────
    customers: "Kunden",
    customer: "Kunde",
    addCustomer: "Kunde hinzufügen",
    editCustomer: "Kunde bearbeiten",
    deleteCustomer: "Kunde löschen",
    noCustomers: "Keine Kunden gefunden",
    guestCustomer: "Gast",
    businessCustomer: "Gewerbe",
    privateCustomer: "Privat",
    totalOrders: "Bestellungen gesamt",
    totalSpent: "Gesamtausgaben",
    lastOrder: "Letzte Bestellung",
    accountType: "Kontotyp",

    // ── Products page ──────────────────────────────────────────
    products: "Produkte",
    addProduct: "Produkt hinzufügen",
    editProduct: "Produkt bearbeiten",
    deleteProduct: "Produkt löschen",
    noProducts: "Keine Produkte gefunden",
    productTitle: "Produkttitel",
    productDescription: "Beschreibung",
    productPrice: "Preis",
    productInventory: "Bestand",
    variants: "Varianten",
    showVariants: "Varianten anzeigen",
    hideVariants: "Varianten ausblenden",
    saveVariants: "Varianten speichern",
    savingVariants: "Wird gespeichert…",
    variantName: "Variantenname",
    variantPrice: "Preis",
    variantInventory: "Bestand",
    variantSku: "SKU",

    // ── Settings ────────────────────────────────────────────────
    settings: "Einstellungen",
    settingsBack: "Zurück",
    settingsTitle: "Einstellungen",
    settingsSubtitle: "Plattform konfigurieren",
    settingsGroupAccount: "Konto",
    settingsGroupTeam: "Team",
    settingsGroupShop: "Shop",
    settingsGroupSystem: "System",
    settingsGeneral: "Allgemein",
    settingsVerification: "Verifizierung",
    settingsBilling: "Abrechnung",
    settingsSecurity: "Sicherheit",
    settingsUsers: "Benutzer & Rechte",
    settingsPayments: "Zahlungen",
    settingsCheckout: "Checkout",
    settingsShipping: "Versand & Lieferung",
    settingsTaxes: "Steuern & Abgaben",
    settingsLocations: "Standorte",
    settingsIntegrations: "Apps & Integrationen",
    settingsNotifications: "Benachrichtigungen",

    // ── General settings ───────────────────────────────────────
    storeName: "Shop-Name",
    email: "E-Mail",
    companyName: "Firmenname (rechtlich)",
    taxId: "Steuernummer",
    vatId: "USt-IdNr.",
    iban: "IBAN (optional)",
    website: "Webseite",
    language: "Sprache",
    address: "Adresse",
    postalCode: "PLZ",
    savedSuccess: "Einstellungen erfolgreich gespeichert.",
    saveError: "Fehler beim Speichern.",
    businessAddress: "Eingetragene Geschäftsadresse",
    warehouseAddress: "Lager / Rücksendeadresse",
    documents: "Unternehmensdokumente",
    uploading: "Dokumente werden hochgeladen…",
    adminInfo: "Admin Informationen (Plattformbetreiber)",
    adminInfoNote: "Diese Angaben erscheinen im unterzeichneten Seller Agreement PDF. Nur für Superuser sichtbar.",

    // ── Billing ─────────────────────────────────────────────────
    orderDocuments: "Bestelldokumente",
    commissionInvoices: "Provisionsrechnungen",
    searchOrderPlaceholder: "Bestellnr. oder Kundenname…",
    from: "Von",
    to: "Bis",
    documentType: "Dokumenttyp",
    allDocuments: "Alle Dokumente",
    invoiceDoc: "Rechnung",
    deliveryNoteDoc: "Lieferschein",
    shippingLabel: "Versandlabel",
    returnDoc: "Retoure",
    csvExport: "CSV Export",
    openInvoices: "Rechnungen öffnen",
    noOrdersFound: "Keine Bestellungen gefunden.",
    period: "Zeitraum",
    type: "Typ",
    amount: "Betrag",
    downloadAll: "Alle herunterladen",
    backfill: "Rückwirkend generieren",
    noInvoices: "Noch keine Provisionsrechnungen vorhanden.",
    noInvoicesNote: "Provisionsrechnungen erscheinen hier, sobald die Plattform diese bereitstellt.",
    platformOwn: "Plattform (eigene)",
    sellerOrders: "Verkäufer-Bestellungen",
    noSellerOrders: "Keine weiteren Verkäufer-Bestellungen",
    superuserSection: "Ihr Superuser-Bereich — eigene Konto-Bestellungen und ohne Verkäufer-Zuordnung",
    noOrdersInSection: "Keine Bestellungen in diesem Bereich.",

    // ── Notifications ──────────────────────────────────────────
    notifications: "Benachrichtigungen",
    noNotifications: "Keine Benachrichtigungen",
    markAsRead: "Als gelesen markieren",
    markAllRead: "Alle als gelesen markieren",

    // ── Misc ───────────────────────────────────────────────────
    netto: "Netto",
    brutto: "Brutto",
    all: "Alle",
    yes: "Ja",
    no: "Nein",
    optional: "optional",
    required: "erforderlich",
    new: "Neu",
    active: "Aktiv",
    inactive: "Inaktiv",
    unknown: "Unbekannt",
  },

  tr: {
    save: "Kaydet", saving: "Kaydediliyor…", saved: "Kaydedildi",
    cancel: "İptal", delete: "Sil", deleting: "Siliniyor…",
    edit: "Düzenle", add: "Ekle", create: "Oluştur", creating: "Oluşturuluyor…",
    update: "Güncelle", close: "Kapat", back: "Geri", next: "İleri", previous: "Geri",
    confirm: "Onayla", remove: "Kaldır", search: "Ara", filter: "Filtrele",
    reset: "Sıfırla", apply: "Uygula", loading: "Yükleniyor…", loadingMore: "Daha fazla yükle…",
    noResults: "Sonuç bulunamadı", noData: "Veri yok", error: "Hata oluştu",
    retry: "Tekrar dene", upload: "Yükle", uploading: "Yükleniyor…",
    download: "İndir", export: "Dışa aktar", import: "İçe aktar",
    send: "Gönder", print: "Yazdır", preview: "Önizleme",
    publish: "Yayınla", unpublish: "Yayından kaldır", archive: "Arşivle",
    duplicate: "Kopyala", select: "Seç", selectAll: "Tümünü seç",
    deselectAll: "Seçimi kaldır", selected: "seçildi", actions: "İşlemler",
    more: "Daha fazla", show: "Göster", hide: "Gizle",
    expand: "Genişlet", collapse: "Daralt", copy: "Kopyala", paste: "Yapıştır",
    refresh: "Yenile", viewDetails: "Detayları görüntüle", viewAll: "Tümünü görüntüle",
    status: "Durum", statusOpen: "Açık", statusInProgress: "İşlemde",
    statusCompleted: "Tamamlandı", statusCancelled: "İptal edildi",
    statusPaid: "Ödendi", statusUnpaid: "Ödenmedi",
    statusPartiallyRefunded: "Kısmen iade edildi", statusRefunded: "İade edildi",
    statusShipped: "Kargoya verildi", statusDelivered: "Teslim edildi",
    statusReturn: "İade", statusReturnRequested: "İade talebi",
    statusDraft: "Taslak", statusPublished: "Yayında", statusArchived: "Arşivlendi",
    statusActive: "Aktif", statusInactive: "Pasif",
    colNumber: "#", colName: "Ad", colTitle: "Başlık", colEmail: "E-posta",
    colPhone: "Telefon", colAddress: "Adres", colCity: "Şehir", colCountry: "Ülke",
    colDate: "Tarih", colCreatedAt: "Oluşturuldu", colUpdatedAt: "Güncellendi",
    colAmount: "Tutar", colTotal: "Toplam", colPrice: "Fiyat", colQuantity: "Adet",
    colInventory: "Stok", colStatus: "Durum", colPaymentStatus: "Ödeme durumu",
    colDeliveryStatus: "Teslimat durumu", colOrderStatus: "Sipariş durumu",
    colOrderNumber: "Sipariş #", colCustomer: "Müşteri", colProduct: "Ürün",
    colSKU: "SKU", colImage: "Görsel", colRating: "Puan", colReview: "Yorum",
    colType: "Tür", colCategory: "Kategori", colDescription: "Açıklama",
    colActions: "İşlemler", colColumns: "Sütunlar", colSeller: "Satıcı",
    orders: "Siparişler", orderNumber: "Sipariş numarası",
    orderStatus: "Sipariş durumu", paymentStatus: "Ödeme durumu",
    deliveryStatus: "Teslimat durumu", allStatuses: "Tüm durumlar",
    allPayments: "Tüm ödemeler", allDeliveries: "Tüm teslimatlar",
    addOrder: "Sipariş ekle", manualOrder: "Manuel Sipariş",
    ship: "Kargola", buyLabel: "Etiket satın al", cancelOrder: "İptal et",
    deleteOrder: "Sil", shippingTracking: "Kargo / Takip",
    carrier: "Kargo firması", noCarrier: "Kargo firması girilmedi",
    trackingNumber: "Takip numarası", enterTrackingNumber: "Takip numarası girin",
    savedTracking: "Kaydedildi:", clickTracking: "— Tıklayarak takip edin",
    noTrackingYet: "Henüz takip numarası yok.",
    invoice: "Fatura (PDF)", deliveryNote: "İrsaliye (PDF)", message: "Mesaj",
    sortNewestFirst: "En yeni önce", sortOldestFirst: "En eski önce",
    amountDesc: "Tutar ↓", amountAsc: "Tutar ↑",
    searchSeller: "Satıcı ara", sellerGroups: "Satıcı gruplarını sırala",
    bulkShip: "Kargola", bulkPackaging: "Paketleme merkezi",
    clearSelection: "Seçimi kaldır", noOrders: "Sipariş bulunamadı",
    loadingOrders: "Yükleniyor…", product: "Ürün", qty: "Adet",
    unitPrice: "Birim fiyat (brüt)", total: "Toplam (brüt)", noItems: "Ürün yok",
    net: "Net", shipping: "Kargo", shippingFree: "Ücretsiz",
    subtotal: "Ara toplam (brüt)", grandTotal: "Genel toplam",
    guestBadge: "Misafir", reviewsTitle: "Müşteri yorumları", noReviews: "Yorum yok.",
    labelSuccess: "Etiket başarıyla oluşturuldu!", labelError: "Etiket oluşturma hatası",
    labelPrint: "Etiketi yazdır (PDF)",
    customerData: "Müşteri bilgileri", firstName: "Ad", lastName: "Soyad",
    phone: "Telefon", country: "Ülke", street: "Sokak", postalCode: "Posta kodu", city: "Şehir",
    items: "Ürünler", itemName: "Ürün adı", itemQty: "Adet", itemPrice: "Fiyat (kuruş)",
    addItem: "Ürün ekle", shippingCents: "Kargo (kuruş)", discountCents: "İndirim (kuruş)",
    orderStatusLabel: "Sipariş durumu", paymentStatusLabel: "Ödeme durumu",
    deliveryStatusLabel: "Teslimat durumu", paymentMethod: "Ödeme yöntemi",
    currency: "Para birimi", notes: "Notlar",
    summarySubtotal: "Ara toplam", summaryShipping: "Kargo",
    summaryDiscount: "İndirim", summaryTotal: "Toplam",
    createOrder: "Sipariş oluştur", filterAndSort: "Filtrele & sırala",
    searchPlaceholder: "Ad, e-posta, sipariş numarası…",
    return: "İade", activeReturn: "İade (aktif)", retoure: "İade",
    customers: "Müşteriler", customer: "Müşteri",
    addCustomer: "Müşteri ekle", editCustomer: "Müşteriyi düzenle",
    deleteCustomer: "Müşteriyi sil", noCustomers: "Müşteri bulunamadı",
    guestCustomer: "Misafir", businessCustomer: "Kurumsal", privateCustomer: "Bireysel",
    totalOrders: "Toplam sipariş", totalSpent: "Toplam harcama",
    lastOrder: "Son sipariş", accountType: "Hesap türü",
    products: "Ürünler", addProduct: "Ürün ekle", editProduct: "Ürünü düzenle",
    deleteProduct: "Ürünü sil", noProducts: "Ürün bulunamadı",
    productTitle: "Ürün başlığı", productDescription: "Açıklama",
    productPrice: "Fiyat", productInventory: "Stok",
    variants: "Varyantlar", showVariants: "Varyantları göster",
    hideVariants: "Varyantları gizle", saveVariants: "Varyantları kaydet",
    savingVariants: "Kaydediliyor…", variantName: "Varyant adı",
    variantPrice: "Fiyat", variantInventory: "Stok", variantSku: "SKU",
    settings: "Ayarlar", settingsBack: "Geri",
    settingsTitle: "Ayarlar", settingsSubtitle: "Platformu yapılandır",
    settingsGroupAccount: "Hesap", settingsGroupTeam: "Ekip",
    settingsGroupShop: "Mağaza", settingsGroupSystem: "Sistem",
    settingsGeneral: "Genel", settingsVerification: "Doğrulama",
    settingsBilling: "Faturalama", settingsSecurity: "Güvenlik",
    settingsUsers: "Kullanıcılar & İzinler", settingsPayments: "Ödemeler",
    settingsCheckout: "Ödeme", settingsShipping: "Kargo & Teslimat",
    settingsTaxes: "Vergiler", settingsLocations: "Konumlar",
    settingsIntegrations: "Uygulamalar & Entegrasyonlar",
    settingsNotifications: "Bildirimler",
    storeName: "Mağaza adı", email: "E-posta", companyName: "Şirket adı",
    taxId: "Vergi numarası", vatId: "KDV numarası", iban: "IBAN (isteğe bağlı)",
    website: "Web sitesi", language: "Dil", address: "Adres",
    savedSuccess: "Ayarlar başarıyla kaydedildi.", saveError: "Ayarlar kaydedilemedi.",
    businessAddress: "Kayıtlı iş adresi", warehouseAddress: "Depo / iade adresi",
    documents: "Şirket belgeleri", uploading: "Belgeler yükleniyor…",
    adminInfo: "Admin Bilgileri (Platform İşletmecisi)",
    adminInfoNote: "Bu bilgiler imzalanan Satıcı Sözleşmesi PDF'inde görünür. Yalnızca süper kullanıcılar görebilir.",
    orderDocuments: "Sipariş Belgeleri", commissionInvoices: "Komisyon Faturaları",
    searchOrderPlaceholder: "Sipariş no. veya müşteri adı…",
    from: "Başlangıç", to: "Bitiş", documentType: "Belge türü",
    allDocuments: "Tüm belgeler", invoiceDoc: "Fatura",
    deliveryNoteDoc: "İrsaliye", shippingLabel: "Kargo etiketi", returnDoc: "İade",
    csvExport: "CSV Dışa Aktar", openInvoices: "Faturaları aç",
    noOrdersFound: "Sipariş bulunamadı.", period: "Dönem", type: "Tür", amount: "Tutar",
    downloadAll: "Tümünü indir", backfill: "Geçmişe dönük oluştur",
    noInvoices: "Henüz komisyon faturası yok.",
    noInvoicesNote: "Komisyon faturaları platform tarafından sağlandığında burada görünür.",
    platformOwn: "Platform (kendi)", sellerOrders: "Satıcı siparişleri",
    noSellerOrders: "Daha fazla satıcı siparişi yok",
    superuserSection: "Süper kullanıcı alanınız — kendi hesap siparişleri ve atanmamış",
    noOrdersInSection: "Bu bölümde sipariş yok.",
    notifications: "Bildirimler", noNotifications: "Bildirim yok",
    markAsRead: "Okundu olarak işaretle", markAllRead: "Tümünü okundu işaretle",
    netto: "Net", brutto: "Brüt", all: "Tümü", yes: "Evet", no: "Hayır",
    optional: "isteğe bağlı", required: "zorunlu", new: "Yeni",
    active: "Aktif", inactive: "Pasif", unknown: "Bilinmiyor",
  },

  fr: {
    save: "Enregistrer", saving: "Enregistrement…", saved: "Enregistré",
    cancel: "Annuler", delete: "Supprimer", deleting: "Suppression…",
    edit: "Modifier", add: "Ajouter", create: "Créer", creating: "Création…",
    update: "Mettre à jour", close: "Fermer", back: "Retour", next: "Suivant", previous: "Précédent",
    confirm: "Confirmer", remove: "Supprimer", search: "Rechercher", filter: "Filtrer",
    reset: "Réinitialiser", apply: "Appliquer", loading: "Chargement…", loadingMore: "Charger plus…",
    noResults: "Aucun résultat", noData: "Aucune donnée", error: "Une erreur est survenue",
    retry: "Réessayer", upload: "Télécharger", uploading: "Téléchargement…",
    download: "Télécharger", export: "Exporter", import: "Importer",
    send: "Envoyer", print: "Imprimer", preview: "Aperçu",
    publish: "Publier", unpublish: "Dépublier", archive: "Archiver",
    duplicate: "Dupliquer", select: "Sélectionner", selectAll: "Tout sélectionner",
    deselectAll: "Désélectionner", selected: "sélectionné(s)", actions: "Actions",
    more: "Plus", show: "Afficher", hide: "Masquer",
    expand: "Développer", collapse: "Réduire", copy: "Copier", paste: "Coller",
    refresh: "Actualiser", viewDetails: "Voir les détails", viewAll: "Voir tout",
    status: "Statut", statusOpen: "Ouvert", statusInProgress: "En cours",
    statusCompleted: "Terminé", statusCancelled: "Annulé",
    statusPaid: "Payé", statusUnpaid: "Non payé",
    statusPartiallyRefunded: "Partiellement remboursé", statusRefunded: "Remboursé",
    statusShipped: "Expédié", statusDelivered: "Livré",
    statusReturn: "Retour", statusReturnRequested: "Retour demandé",
    statusDraft: "Brouillon", statusPublished: "Publié", statusArchived: "Archivé",
    statusActive: "Actif", statusInactive: "Inactif",
    orders: "Commandes", settings: "Paramètres", settingsBack: "Retour",
    settingsTitle: "Paramètres", settingsSubtitle: "Configurer la plateforme",
    settingsGroupAccount: "Compte", settingsGroupTeam: "Équipe",
    settingsGroupShop: "Boutique", settingsGroupSystem: "Système",
    settingsGeneral: "Général", settingsVerification: "Vérification",
    settingsBilling: "Facturation", settingsSecurity: "Sécurité",
    settingsUsers: "Utilisateurs & Permissions", settingsPayments: "Paiements",
    settingsCheckout: "Paiement", settingsShipping: "Livraison",
    settingsTaxes: "Taxes", settingsLocations: "Emplacements",
    settingsIntegrations: "Applications & Intégrations",
    settingsNotifications: "Notifications",
    loading: "Chargement…", noResults: "Aucun résultat",
    filterAndSort: "Filtrer & trier", searchPlaceholder: "Nom, e-mail, numéro de commande…",
    addOrder: "Ajouter une commande", noOrders: "Aucune commande trouvée",
    customers: "Clients", products: "Produits",
    netto: "Net", brutto: "Brut", all: "Tout", yes: "Oui", no: "Non",
    optional: "optionnel", required: "obligatoire", new: "Nouveau",
    active: "Actif", inactive: "Inactif", unknown: "Inconnu",
  },

  es: {
    save: "Guardar", saving: "Guardando…", saved: "Guardado",
    cancel: "Cancelar", delete: "Eliminar", deleting: "Eliminando…",
    edit: "Editar", add: "Agregar", create: "Crear", creating: "Creando…",
    update: "Actualizar", close: "Cerrar", back: "Volver", next: "Siguiente", previous: "Anterior",
    confirm: "Confirmar", remove: "Eliminar", search: "Buscar", filter: "Filtrar",
    reset: "Restablecer", apply: "Aplicar", loading: "Cargando…", loadingMore: "Cargando más…",
    noResults: "No se encontraron resultados", noData: "Sin datos", error: "Se produjo un error",
    retry: "Reintentar", upload: "Subir", uploading: "Subiendo…",
    download: "Descargar", export: "Exportar", import: "Importar",
    send: "Enviar", print: "Imprimir", preview: "Vista previa",
    publish: "Publicar", unpublish: "Despublicar", archive: "Archivar",
    duplicate: "Duplicar", select: "Seleccionar", selectAll: "Seleccionar todo",
    deselectAll: "Deseleccionar", selected: "seleccionado(s)", actions: "Acciones",
    more: "Más", show: "Mostrar", hide: "Ocultar",
    expand: "Expandir", collapse: "Colapsar", copy: "Copiar", paste: "Pegar",
    refresh: "Actualizar", viewDetails: "Ver detalles", viewAll: "Ver todo",
    status: "Estado", statusOpen: "Abierto", statusInProgress: "En proceso",
    statusCompleted: "Completado", statusCancelled: "Cancelado",
    statusPaid: "Pagado", statusUnpaid: "Sin pagar",
    statusPartiallyRefunded: "Reembolsado parcialmente", statusRefunded: "Reembolsado",
    statusShipped: "Enviado", statusDelivered: "Entregado",
    statusReturn: "Devolución", statusReturnRequested: "Devolución solicitada",
    statusDraft: "Borrador", statusPublished: "Publicado", statusArchived: "Archivado",
    statusActive: "Activo", statusInactive: "Inactivo",
    orders: "Pedidos", settings: "Ajustes", settingsBack: "Volver",
    settingsTitle: "Ajustes", settingsSubtitle: "Configurar plataforma",
    settingsGroupAccount: "Cuenta", settingsGroupTeam: "Equipo",
    settingsGroupShop: "Tienda", settingsGroupSystem: "Sistema",
    settingsGeneral: "General", settingsVerification: "Verificación",
    settingsBilling: "Facturación", settingsSecurity: "Seguridad",
    settingsUsers: "Usuarios & Permisos", settingsPayments: "Pagos",
    settingsCheckout: "Pago", settingsShipping: "Envío & Entrega",
    settingsTaxes: "Impuestos", settingsLocations: "Ubicaciones",
    settingsIntegrations: "Aplicaciones & Integraciones",
    settingsNotifications: "Notificaciones",
    loading: "Cargando…", noResults: "Sin resultados",
    filterAndSort: "Filtrar & ordenar", searchPlaceholder: "Nombre, correo, número de pedido…",
    addOrder: "Agregar pedido", noOrders: "No se encontraron pedidos",
    customers: "Clientes", products: "Productos",
    netto: "Neto", brutto: "Bruto", all: "Todo", yes: "Sí", no: "No",
    optional: "opcional", required: "obligatorio", new: "Nuevo",
    active: "Activo", inactive: "Inactivo", unknown: "Desconocido",
  },

  it: {
    save: "Salva", saving: "Salvataggio…", saved: "Salvato",
    cancel: "Annulla", delete: "Elimina", deleting: "Eliminazione…",
    edit: "Modifica", add: "Aggiungi", create: "Crea", creating: "Creazione…",
    update: "Aggiorna", close: "Chiudi", back: "Indietro", next: "Avanti", previous: "Precedente",
    confirm: "Conferma", remove: "Rimuovi", search: "Cerca", filter: "Filtra",
    reset: "Reimposta", apply: "Applica", loading: "Caricamento…", loadingMore: "Carica altro…",
    noResults: "Nessun risultato", noData: "Nessun dato", error: "Si è verificato un errore",
    retry: "Riprova", upload: "Carica", uploading: "Caricamento…",
    download: "Scarica", export: "Esporta", import: "Importa",
    send: "Invia", print: "Stampa", preview: "Anteprima",
    publish: "Pubblica", unpublish: "Rimuovi pubblicazione", archive: "Archivia",
    duplicate: "Duplica", select: "Seleziona", selectAll: "Seleziona tutto",
    deselectAll: "Deseleziona", selected: "selezionato/i", actions: "Azioni",
    more: "Altro", show: "Mostra", hide: "Nascondi",
    expand: "Espandi", collapse: "Comprimi", copy: "Copia", paste: "Incolla",
    refresh: "Aggiorna", viewDetails: "Visualizza dettagli", viewAll: "Visualizza tutto",
    status: "Stato", statusOpen: "Aperto", statusInProgress: "In corso",
    statusCompleted: "Completato", statusCancelled: "Annullato",
    statusPaid: "Pagato", statusUnpaid: "Non pagato",
    statusPartiallyRefunded: "Parzialmente rimborsato", statusRefunded: "Rimborsato",
    statusShipped: "Spedito", statusDelivered: "Consegnato",
    statusReturn: "Reso", statusReturnRequested: "Reso richiesto",
    statusDraft: "Bozza", statusPublished: "Pubblicato", statusArchived: "Archiviato",
    statusActive: "Attivo", statusInactive: "Inattivo",
    orders: "Ordini", settings: "Impostazioni", settingsBack: "Indietro",
    settingsTitle: "Impostazioni", settingsSubtitle: "Configura piattaforma",
    settingsGroupAccount: "Account", settingsGroupTeam: "Team",
    settingsGroupShop: "Negozio", settingsGroupSystem: "Sistema",
    settingsGeneral: "Generale", settingsVerification: "Verifica",
    settingsBilling: "Fatturazione", settingsSecurity: "Sicurezza",
    settingsUsers: "Utenti & Permessi", settingsPayments: "Pagamenti",
    settingsCheckout: "Checkout", settingsShipping: "Spedizione & Consegna",
    settingsTaxes: "Tasse", settingsLocations: "Posizioni",
    settingsIntegrations: "App & Integrazioni",
    settingsNotifications: "Notifiche",
    loading: "Caricamento…", noResults: "Nessun risultato",
    filterAndSort: "Filtra & ordina", searchPlaceholder: "Nome, e-mail, numero ordine…",
    addOrder: "Aggiungi ordine", noOrders: "Nessun ordine trovato",
    customers: "Clienti", products: "Prodotti",
    netto: "Netto", brutto: "Lordo", all: "Tutti", yes: "Sì", no: "No",
    optional: "opzionale", required: "obbligatorio", new: "Nuovo",
    active: "Attivo", inactive: "Inattivo", unknown: "Sconosciuto",
  },
};

/**
 * Get UI strings for a given locale. Falls back to English for missing keys.
 */
export function getUI(locale) {
  const base = UI_STRINGS.en;
  const overrides = UI_STRINGS[locale] || {};
  return { ...base, ...overrides };
}

/**
 * React hook — reads locale from localStorage (sellerLocale) or defaults to "de".
 * Call at top of component: const ui = useUI();
 */
export function useUI() {
  if (typeof window === "undefined") return getUI("de");
  const locale =
    (typeof localStorage !== "undefined" && localStorage.getItem("sellerLocale")) ||
    document.documentElement.lang ||
    "de";
  return getUI(locale);
}

/**
 * useUILocale — same as useUI but also returns the locale string.
 */
export function useUILocale() {
  if (typeof window === "undefined") return { ui: getUI("de"), locale: "de" };
  const locale =
    (typeof localStorage !== "undefined" && localStorage.getItem("sellerLocale")) ||
    document.documentElement.lang ||
    "de";
  return { ui: getUI(locale), locale };
}
